### ISSUE TITLE
Support for Windows 10

### ISSUE THREAD

**Issue by Alloyd031** [Gaoyifei1011/WindowsToolbox#1]
Is there will be a support for Windows 10? I wanted to run this app on this OS but it's not supported.

**Comment by Gaoyifei1011** [comment]
> Is there will be a support for Windows 10? I wanted to run this app on this OS but it's not supported.

My application was put into the minimum requirement Windows 10 19041, maybe some of the api occurred incompatible phenomenon, resulting in application startup failure. Due to personal reasons, I can only test on the platform of 22621+, I am sorry for not testing on the platform below 22621. I will test in the virtual machine later and find the corresponding problem, and release the fix pack after solving it. Thank you very much.
我的应用放到最低要求Windows 10 19041了，也许可能有部分api发生了不兼容现象导致应用启动失败。由于个人原因，我只能在22621+的平台上进行测试，没有在低于22621的平台上进行测试很抱歉。我会稍后在虚拟机中进行测试并寻找相应的问题，待到解决后发布修复包，非常感谢。

**Comment by Gaoyifei1011** [comment]
> Is there will be a support for Windows 10? I wanted to run this app on this OS but it's not supported.

![image](https://github.com/Gaoyifei1011/WindowsToolbox/assets/49179966/b00d0d01-1e8b-490d-ae69-e7f93e61a0ad)
Uh, all right. It should be my mistake. The problem comes from the fact that I used an API supported by Windows 11 22621+ last time, and forgot to modify the minimum version limit after using an API that can be used in a lower version of the system. I will release a fixed version later. You can pull the code and modify the MinVersion value of packagemanifest.xml to use on Windows 10, thank you very much
额，好吧。应该是我的失误，问题来源于上次使用了一个 Windows 11 22621+ 支持的 API，然后使用了一个可以在低版本系统使用的 API 后忘记修改最低版本限制了，我会在稍后发布修复版本，您可以拉取代码然后修改 packagemanifest.xml 的 MinVersion 值在 Windows 10 上面使用，非常感谢

**Comment by Gaoyifei1011** [comment]
> Is there will be a support for Windows 10? I wanted to run this app on this OS but it's not supported.

The issue has been fixed. A new version has been released
问题已修复。已发布新版本

**Comment by Alloyd031** [comment]
The app still doesn't install on Windows 10.

**Comment by Gaoyifei1011** [comment]
> The app still doesn't install on Windows 10.

I have noted the problem you mentioned. I found that determining the minimum version of the project is not defined by the minimum version of Package.appxmanifest, but by the TargetPlatformVersion and TargetPlatformMinVersion attributes of the Wapproj, I will keep a log of this issue and post an updated fix after a certain period of time

我注意到您提到的问题了。我发现决定项目的最低版本不是由 Package.appxmanifest 的最低版本定义，而是在 Wapproj 的 TargetPlatformVersion 和 TargetPlatformMinVersion 这两个属性决定的，这个问题我将持续记录，并在一定时间段后发布更新的修复版本

wapproj properties
![image](https://github.com/user-attachments/assets/4d4f05f3-1739-4ee5-9600-81570586b08f)

Package.appxmanifest settings
![image](https://github.com/user-attachments/assets/832adf88-a16f-4cf8-a08e-29b09bcdeebb)

**Comment by Alloyd031** [comment]
App Installer still thinks that the minimum version is Windows 11

**Comment by Gaoyifei1011** [comment]
> App Installer still thinks that the minimum version is Windows 11

Problems have  been fixed.A new version has been released. (https://github.com/Gaoyifei1011/WindowsToolbox/releases)
![{2027C464-79F7-40E6-A9B8-986DBD355FAE}](https://github.com/user-attachments/assets/26921223-3860-4d0b-98c0-75fcf3af12c7)

**Comment by Alloyd031** [comment]
Thank you! Now i can close this issue.
